### ISSUE TITLE
JSON loading issues

### ISSUE THREAD

**Issue by kurransingh** [nicrip/SynchronySDK_py#1]
Hi,
I am encountering issues with uploading odometry measurements. I am using Python 2.7 and attempting to upload the following inputs that are identical to those used without error in the hexagonal_example.py:

 delta_measurement = np.array([[10.0], [0], [np.pi/3.0]])
 p_odo = np.array([[0.1, 0.0, 0.0],[0.0, 0.1, 0.0],[0.0, 0.0, 0.1]])

The error message is as follows:
[ERROR] [1533070550.327240]: bad callback: <function detection_callback at 0x7f5fbbeb9f50>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "factorUploading.py", line 127, in detection_callback
    add_odo_response = addNodeFactor_OdoNormal(navi, time.time(), robotId, sessionId, delta_measurement, p_odo)
  File "/home/singhk/catkin_ws/src/NaviUtils.py", line 7, in addNodeFactor_OdoNormal
    return navi.addOdometryMeasurement(robotname, sessionname, new_odometry_measurement)
  File "/home/singhk/catkin_ws/src/Navi.py", line 261, in addOdometryMeasurement
    return GenericResponse(response.content)
  File "/home/singhk/catkin_ws/src/Navi.py", line 21, in __init__
    json_val = json.loads(json_str)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

The first upload of odometry in a given session is successful, but subsequent attempts to upload identical odometry after uploading other factors and landmarks causes the above error to be thrown. 
The hexagonal example uploads all six odometry measurements before adding any landmarks etc, which is probably why it runs successfully. 
Any help would be greatly appreciated.
Thanks!

**Comment by nicrip** [comment]
Usually when it comes back with an error like this, I do a print to see what was actually returned - so in addOdometryMeasurement, line 258, I would put:

print response

its likely that the server is responding with a 500 error, which would mean it is a backend problem.

**Comment by dehann** [comment]
always blaming the backend...

**Comment by nicrip** [comment]
lol! If I knew more about the backend I could help :P

**Comment by dehann** [comment]
Hi, so the server api has been fixed.  You can try it again thanks.
